jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: pg
      user: alice
      pass: postgres
      port: 5432
      dbname: jaffle_shop
      schema: dbt_alice
      threads: 1
